[Audio]
Volume=100

[General]
AppendVideoToSingleInstance=true
ColorScheme=Default
FooterStyle=floating
FullscreenOnStartUp=true
GuiStyle=Breeze
LastPlayedFile=https://video.wixstatic.com/video/dd6e23_16f37eeb30d74c0785aff349c0de8177/1080p/mp4/file.mp4
ShowPreviewThumbnail=true
UseSingleInstance=true

[Playback]
ChaptersToSkip=Opening,Ending
OpenLastPlayedFile=true
PauseWhileMinimized=true
RestoreFilePosition=true
SkipChapters=true

[Playlist]
PlaybackBehavior=StopAfterLast
PlaylistWidth=191.17647058823528
ShowToolbar=false
Style=withThumbnails
