[Audio]
Volume=100

[General]
AppendVideoToSingleInstance=true
ColorScheme=Default
FooterStyle=floating
FullscreenOnStartUp=true
GuiStyle=Breeze
LastPlayedFile=https://myanime.sharepoint.com/sites/anime2/_layouts/15/download.aspx?share=IQDH2JpRmIC3Q66QrUj2dB7aASDgYAd7iYY0DUVsl4j9SR4
LastUrl=https://www.youtube.com/watch?v=Sx9zG7wa4FA&t=335s
ShowPreviewThumbnail=true
UseSingleInstance=true

[Playback]
ChaptersToSkip=Opening,Ending
OpenLastPlayedFile=true
PauseWhileMinimized=true
RestoreFilePosition=true
SkipChapters=true
YtdlFormat=bestvideo[height<=1080]+bestaudio/best

[Playlist]
PlaybackBehavior=StopAfterLast
PlaylistWidth=191.17647058823528
ShowToolbar=false
Style=withThumbnails
Visible=true
